# Generated by Django 4.0.4 on 2022-05-08 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Employee Name')),
                ('emp_code', models.IntegerField(verbose_name='Employee Code')),
                ('salary', models.IntegerField(verbose_name='Salary')),
                ('band', models.CharField(choices=[('S0', 'S0'), ('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3'), ('S4', 'S4'), ('S5', 'S5')], default='S0', max_length=50, verbose_name='Band Level')),
                ('department', models.CharField(choices=[('DEV', 'Development'), ('FIN', 'Finance'), ('HR', 'Human Resource'), ('TA', 'Talent Acquisition'), ('Admin', 'Administration')], default='Development', max_length=50, verbose_name='Department')),
                ('location', models.CharField(max_length=50, verbose_name='Job Location')),
                ('emp_type', models.CharField(choices=[('Permanent', 'Permanent'), ('Temporary', 'Temporary'), ('Internship', 'Internship')], default='Permanent', max_length=50, verbose_name='Employment Type')),
                ('email', models.EmailField(max_length=50, verbose_name='Email Address')),
            ],
        ),
    ]
