# Generated by Django 4.0.4 on 2022-05-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(help_text='Title for the type of API', max_length=200, verbose_name='API Type')),
                ('desc', models.TextField(help_text='Describe a little about this API', verbose_name='Description')),
                ('test_link1', models.CharField(help_text='Link to test the API', max_length=50, verbose_name='API Link 1')),
                ('test_link2', models.CharField(help_text='Link to test the API', max_length=50, verbose_name='API Link 2')),
            ],
        ),
    ]
